// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUFliJplMCNhKr0_ym6LJCPZX5m7M2PAY',
    appId: '1:545905775326:web:386555274580b1f443284f',
    messagingSenderId: '545905775326',
    projectId: 'hiwork-cd1b6',
    authDomain: 'hiwork-cd1b6.firebaseapp.com',
    storageBucket: 'hiwork-cd1b6.firebasestorage.app',
    measurementId: 'G-BPQEP98H1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoDQ7eQ0dUVv6x9ZM3eZUseyMwkvgcHWY',
    appId: '1:545905775326:android:f3d1e78cf9081f7e43284f',
    messagingSenderId: '545905775326',
    projectId: 'hiwork-cd1b6',
    storageBucket: 'hiwork-cd1b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuajlEC6ODx5rRQjuHKvtTOQhy9s9Zsx8',
    appId: '1:545905775326:ios:4a8a17f5b10572fd43284f',
    messagingSenderId: '545905775326',
    projectId: 'hiwork-cd1b6',
    storageBucket: 'hiwork-cd1b6.firebasestorage.app',
    iosBundleId: 'com.example.hiworkMo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuajlEC6ODx5rRQjuHKvtTOQhy9s9Zsx8',
    appId: '1:545905775326:ios:4a8a17f5b10572fd43284f',
    messagingSenderId: '545905775326',
    projectId: 'hiwork-cd1b6',
    storageBucket: 'hiwork-cd1b6.firebasestorage.app',
    iosBundleId: 'com.example.hiworkMo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUFliJplMCNhKr0_ym6LJCPZX5m7M2PAY',
    appId: '1:545905775326:web:3889761c26f4d8f143284f',
    messagingSenderId: '545905775326',
    projectId: 'hiwork-cd1b6',
    authDomain: 'hiwork-cd1b6.firebaseapp.com',
    storageBucket: 'hiwork-cd1b6.firebasestorage.app',
    measurementId: 'G-LP2ZPZYGJE',
  );
}
